apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: vllm-deploy
  ports:
  - port: 8000
    targetPort: 8000
    # NodePort 端口范围：30000-32767
    # 请确保 ${SERVICE_PORT} 在此范围内
    nodePort: ${SERVICE_PORT}
    protocol: TCP
    name: vllm-api